deprecates Go 1.5 in .travis.ymml
This Extension is using golint (github.com/golang/lint/golint) that
requires at least Go 1.6.
It results as an error during the CI install step in travis-ci for the
target envs go.1.5 linux and osx.
error: ../../golang/lint/lint.go:250: undefined: types.ImportMode

modifications done:
- Remove enx"Go 1.5"
- Update the Readme in order to inform users that this Extension
  requires at least Go 1.6.