Copy formatFlags before modifications (#1334)
The workspace config objects are frozen causing the error

```
TypeError: Cannot add property 0, object is not extensible
```

Easiest solution is to just dupe the array before doing anything to it.